BASE_GRAPH_URL = 'https://graph.facebook.com'
BASE_AUTHORIZATION_URL = 'https://www.facebook.com'

GRAPH_VERSION_V2_2 = 'v2.2'
GRAPH_VERSION_V2_3 = 'v2.3'
GRAPH_VERSION_V2_4 = 'v2.4'
GRAPH_VERSION_V2_5 = 'v2.5'
GRAPH_VERSION_V2_6 = 'v2.6'
GRAPH_VERSION_V2_7 = 'v2.7'

ISO_8601_DATE_FORMAT = '%Y-%m-%dT%H:%M:%S%z'

DEFAULT_GRAPH_VERSION = GRAPH_VERSION_V2_5
DEFAULT_REQUEST_TIMEOUT = 60

METHOD_DELETE = 'DELETE'
METHOD_GET = 'GET'
METHOD_POST = 'POST'
METHOD_PUT = 'PUT'
